name: CI

on: 
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      version:
        default: 1.0.0
  
permissions:
  checks: write
  pull-requests: write
  id-token: write
  contents: write
  pages: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Github actions have Node and Yarn already set-up by default
    # It is not clear which versions these are, 
    # so it might be a good idea to specify them via an action like actions/setup-node@v4
    - uses: actions/checkout@v4
    - name: Install
      run: yarn
    - name: Unit tests
      run: yarn test
    - name: Build
      run: yarn build
    - name: Integration tests
      run: yarn test:e2e
    - name: Publish unit test results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: 'reports/*.xml'
    - name: Create and push tag
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v${{ inputs.version }}" -m "Release version ${{ inputs.version }}"
        git push origin "v${{ inputs.version }}"

